name: cypress testes

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs:
  cyrpess-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Dependencias
        run: npm install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}

      #- name: cypress run
       # uses: cypress-io/github-action@v5.0.8
        #with:
         # browser: chrome

      