name: cypress testes

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs:
  cyrpess-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Dependencias
        run: yarn install

      - name: cypress run
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: electron
          group: UI Electron

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}

  cyrpess-E2E-chrome:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Dependencias
          run: yarn install

        - name: Run E2E tests
          run: ${{ github.event.inputs.cli }}

        - name: cypress run
          uses: cypress-io/github-action@v5.0.8
          with:
            install-command: yarn install
            browser: chrome
            group: UI Chrome

  cyrpess-E2E-firefox:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.2

          - name: Dependencias
            run: yarn install

          - name: Run E2E tests
            run: ${{ github.event.inputs.cli }}

          - name: cypress run
            uses: cypress-io/github-action@v5.0.8
            with:
              install-command: yarn install
              browser: firefox
              group: UI Firefox

      