name: Executar Testes

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'  # Executa às 05h (horário de Brasília)

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, chrome, firefox]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes no ${{ matrix.browser }}
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: ${{ matrix.browser }}

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-${{ matrix.browser }}
          path: cypress/reports

      - name: Upload Screenshots (condicional)
        if: always()
        run: |
          if [ -d "cypress/screenshots" ] && [ "$(ls -A cypress/screenshots)" ]; then
            echo "Uploading screenshots..."
            tar -cvf screenshots-${{ matrix.browser }}.tar cypress/screenshots
          else
            echo "No screenshots to upload"
          fi
      - name: Enviar Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.browser }}
          path: screenshots-${{ matrix.browser }}.tar

      - name: Upload Videos (condicional)
        if: always()
        run: |
          if [ -d "cypress/videos" ] && [ "$(ls -A cypress/videos)" ]; then
            echo "Uploading videos..."
            tar -cvf videos-${{ matrix.browser }}.tar cypress/videos
          else
            echo "No videos to upload"
          fi
      - name: Enviar Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.browser }}
          path: videos-${{ matrix.browser }}.tar
