name: Cypress - Testes Cross-Browser

on:
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    name: Cypress - Electron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Instalar e rodar testes no Electron
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: electron
          install-command: yarn install
          group: UI Electron

  cypress-chrome-tests:
    name: Cypress - Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Instalar e rodar testes no Chrome
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome
          install-command: yarn install
          group: UI Chrome

  cypress-firefox-tests:
    name: Cypress - Firefox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Instalar e rodar testes no Firefox
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: firefox
          install-command: yarn install
          group: UI Firefox
