name: Executar Testes

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'  # Executa às 05h (horário de Brasília)

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes no Electron
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: electron

  cypress-E2E-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes no Chrome
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: chrome

cypress-E2E-Firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes no Chrome
        uses: cypress-io/github-action@v5.0.8
        with:
          browser: firefox
