name: Cypress - Testes Cross-browser

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar dependências
        run: yarn install

      - name: Rodar Cypress - Electron
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: electron
          group: UI Electron

  cypress-E2E-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar dependências
        run: yarn install

      - name: Rodar Cypress - Chrome
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: chrome
          group: UI Chrome

  cypress-E2E-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Instalar dependências
        run: yarn install

      - name: Rodar Cypress - Firefox
        uses: cypress-io/github-action@v5.0.8
        with:
          install-command: yarn install
          browser: firefox
          group: UI Firefox
